d_municipio = {
    1:"ACONCHI",
    2:"AGUA_PRIETA",
    3:"ALAMOS",
    4:"ALTAR",
    5:"ARIVECHI",
    6:"ARIZPE",
    7:"ATIL",
    8:"BACADÉHUACHI",
    9:"BACANORA",
    10:"BACERAC",
    11:"BACOACHI",
    12:"BÁCUM",
    13:"BANÁMICHI",
    14:"BAVIÁCORA",
    15:"BAVISPE",
    16:"BENJAMÍN_HILL",
    17:"CABORCA",
    18:"CAJEME",
    19:"CANANEA",
    20:"CARBÓ",
    21:"LA_COLORADA",
    22:"CUCURPE",
    23:"CUMPAS",
    24:"DIVISADEROS",
    25:"EMPALME",
    26:"ETCHOJOA",
    27:"FRONTERAS",
    28:"GRANADOS",
    29:"GUAYMAS",
    30:"HERMOSILLO",
    31:"HUACHINERA",
    32:"HUÁSABAS",
    33:"HUATABAMPO",
    34:"HUÉPAC",
    35:"IMURIS",
    36:"MAGDALENA",
    37:"MAZATÁN",
    38:"MOCTEZUMA",
    39:"NACO",
    40:"NÁCORI_CHICO",
    41:"NACOZARI_DE_GARCÍA",
    42:"NAVOJOA",
    43:"NOGALES",
    44:"ONAVAS",
    45:"OPODEPE",
    46:"OQUITOA",
    47:"PITIQUITO",
    48:"PUERTO_PEÑASCO",
    49:"QUIRIEGO",
    50:"RAYÓN",
    51:"ROSARIO",
    52:"SAHUARIPA",
    53:"SAN_FELIPE_DE_JESÚS",
    54:"SAN_JAVIER",
    55:"SAN_LUIS_RÍO_COLORADO",
    56:"SAN_MIGUEL_DE_HORCASITAS",
    57:"SAN_PEDRO_DE_LA_CUEVA",
    58:"SANTA_ANA",
    59:"SANTA_CRUZ",
    60:"SÁRIC",
    61:"SOYOPA",
    62:"SUAQUI_GRANDE",
    63:"TEPACHE",
    64:"TRINCHERAS",
    65:"TUBUTAMA",
    66:"URES",
    67:"VILLA_HIDALGO",
    68:"VILLA_PESQUEIRA",
    69:"YÉCORA",
    70:"GENERAL_PLUTARCO_ELÍAS_CALLES",
    71:"BENITO_JUÁREZ",
    72:"SAN_IGNACIO_RÍO_MUERTO",
    999:"NO_ESPECIFICADO"
}

d_resultado = {
    1: "Positivo SARS-CoV-2",
    2: "No positivo SARS-CoV-2",
    3: "Resultado pendiente",
    4: "Resultado no adecuado",
    97: "No aplica (sin muestra)"
}

d_clas_fin = {
    1: "Caso de SARS-CoV2 confirmado por asociación clínica epidemiólogica",
    2: "Caso de SARS-CoV2 confirmado por comité de dictaminación",
    3: "Caso de SARS-CoV2 confirmado",
    4: "Inválido por laboratorio",
    5: "No realizado por laboratorio",
    6: "Caso sospechoso",
    7: "Negativo a SARS-Cov2"
}